/**
 * Catalog of user queries with ideal routing metadata.
 * Validated via scripts/dev/validate-user-query-catalog.mts
 */
export type UserQueryExpectation = {
  query: string;
  idealIntent: "HEALTH" | "WEALTH" | "HAPPINESS" | "WISDOM" | "GENERAL";
  idealCapability: string;
  category: string;
  hints: Partial<{
    explicit_meal_log: boolean;
    looks_like_youtube_action: boolean;
    looks_like_magnus_tool_action: boolean;
    looks_like_health_fitness_read: boolean;
    looks_like_wealth_portfolio_read: boolean;
  }>;
  magnusTools?: boolean;
  youtubeAction?: boolean;
  /** Pillars that should appear in pillar_consultation resolution */
  consultPillars?: Array<"HEALTH" | "WEALTH" | "HAPPINESS" | "WISDOM">;
  notes?: string;
};

export const USER_QUERY_CATALOG: UserQueryExpectation[] = [
  // —— HEALTH: explicit meal log (deterministic → HEALTH) ——
  {
    category: "health_meal_log",
    query: "meal: chicken rice and dal",
    idealIntent: "HEALTH",
    idealCapability: "meal_log",
    hints: { explicit_meal_log: true },
  },
  {
    category: "health_meal_log",
    query: "/meal oats and banana",
    idealIntent: "HEALTH",
    idealCapability: "meal_log",
    hints: { explicit_meal_log: true },
  },
  {
    category: "health_meal_log",
    query: "log meal: paneer tikka",
    idealIntent: "HEALTH",
    idealCapability: "meal_log",
    hints: { explicit_meal_log: true },
  },
  {
    category: "health_meal_log",
    query: "ate: scrambled eggs and toast",
    idealIntent: "HEALTH",
    idealCapability: "meal_log",
    hints: { explicit_meal_log: true },
  },
  {
    category: "health_meal_log",
    query: "just had: protein shake",
    idealIntent: "HEALTH",
    idealCapability: "meal_log",
    hints: { explicit_meal_log: true },
  },
  {
    category: "health_meal_log",
    query: "log breakfast: oats and berries",
    idealIntent: "HEALTH",
    idealCapability: "meal_log",
    hints: { explicit_meal_log: true },
  },
  {
    category: "health_meal_log",
    query: "log lunch: chicken salad",
    idealIntent: "HEALTH",
    idealCapability: "meal_log",
    hints: { explicit_meal_log: true },
  },
  {
    category: "health_meal_log",
    query: "log dinner: salmon and veggies",
    idealIntent: "HEALTH",
    idealCapability: "meal_log",
    hints: { explicit_meal_log: true },
  },
  {
    category: "health_meal_log",
    query: "log snack: almonds and apple",
    idealIntent: "HEALTH",
    idealCapability: "meal_log",
    hints: { explicit_meal_log: true },
  },
  {
    category: "health_meal_log",
    query: "/meal@MagnusBot rice bowl",
    idealIntent: "HEALTH",
    idealCapability: "meal_log",
    hints: { explicit_meal_log: true },
  },

  // —— HEALTH: meal history & targets ——
  {
    category: "health_meal_history",
    query: "what did I eat today?",
    idealIntent: "HEALTH",
    idealCapability: "meal_history",
    hints: {},
  },
  {
    category: "health_meal_history",
    query: "what did I eat yesterday?",
    idealIntent: "HEALTH",
    idealCapability: "meal_history",
    hints: {},
  },
  {
    category: "health_meal_history",
    query: "show my meals this week",
    idealIntent: "HEALTH",
    idealCapability: "meal_history",
    hints: {},
  },
  {
    category: "health_meal_history",
    query: "meal breakdown",
    idealIntent: "HEALTH",
    idealCapability: "meal_breakdown",
    hints: {},
  },
  {
    category: "health_meal_history",
    query: "undo my last meal",
    idealIntent: "HEALTH",
    idealCapability: "meal_history_undo",
    hints: {},
  },
  {
    category: "health_meal_history",
    query: "delete the last meal log",
    idealIntent: "HEALTH",
    idealCapability: "meal_history_undo",
    hints: {},
  },
  {
    category: "health_meal_targets",
    query: "show my macro targets",
    idealIntent: "HEALTH",
    idealCapability: "meal_targets_show",
    hints: {},
  },
  {
    category: "health_meal_targets",
    query: "set protein to 140g daily",
    idealIntent: "HEALTH",
    idealCapability: "meal_targets_set",
    hints: {},
  },
  {
    category: "health_meal_targets",
    query: "set calories to 2200",
    idealIntent: "HEALTH",
    idealCapability: "meal_targets_set",
    hints: {},
  },

  // —— HEALTH: meal planning ——
  {
    category: "health_meal_plan",
    query: "plan my meals for the week",
    idealIntent: "HEALTH",
    idealCapability: "meal_plan_create",
    hints: {},
  },
  {
    category: "health_meal_plan",
    query: "help me build a meal plan for next week",
    idealIntent: "HEALTH",
    idealCapability: "meal_plan_create",
    hints: {},
  },
  {
    category: "health_meal_plan",
    query: "what am I eating tomorrow?",
    idealIntent: "HEALTH",
    idealCapability: "meal_plan_read",
    hints: {},
  },
  {
    category: "health_meal_plan",
    query: "show my meal plan for Monday",
    idealIntent: "HEALTH",
    idealCapability: "meal_plan_read",
    hints: {},
  },
  {
    category: "health_meal_plan",
    query: "skip lunch tomorrow",
    idealIntent: "HEALTH",
    idealCapability: "meal_plan_skip",
    hints: {},
  },
  {
    category: "health_meal_plan",
    query: "swap dinner for salad tomorrow",
    idealIntent: "HEALTH",
    idealCapability: "meal_plan_swap",
    hints: {},
  },
  {
    category: "health_meal_plan",
    query: "switch lunch and dinner for today",
    idealIntent: "HEALTH",
    idealCapability: "meal_plan_switch_slots",
    hints: {},
  },
  {
    category: "health_meal_plan",
    query: "copy last week meal plan",
    idealIntent: "HEALTH",
    idealCapability: "meal_plan_copy_week",
    hints: {},
  },
  {
    category: "health_meal_plan",
    query: "save as template high protein",
    idealIntent: "HEALTH",
    idealCapability: "meal_plan_template_save",
    hints: {},
  },
  {
    category: "health_meal_plan",
    query: "list meal plan templates",
    idealIntent: "HEALTH",
    idealCapability: "meal_plan_templates_list",
    hints: {},
  },
  {
    category: "health_meal_plan",
    query: "apply template high protein",
    idealIntent: "HEALTH",
    idealCapability: "meal_plan_template_apply",
    hints: {},
  },
  {
    category: "health_meal_plan",
    query: "shopping list for this week",
    idealIntent: "HEALTH",
    idealCapability: "meal_plan_shopping_list",
    hints: {},
  },
  {
    category: "health_meal_plan",
    query: "grocery list from my meal plan",
    idealIntent: "HEALTH",
    idealCapability: "meal_plan_shopping_list",
    hints: {},
  },

  // —— HEALTH: coaching & specialists ——
  {
    category: "health_fitness",
    query: "should I train legs today?",
    idealIntent: "HEALTH",
    idealCapability: "fitness",
    hints: {},
    magnusTools: false,
  },
  {
    category: "health_fitness",
    query: "what's my gym session today?",
    idealIntent: "HEALTH",
    idealCapability: "fitness",
    hints: { looks_like_health_fitness_read: true },
  },
  {
    category: "health_fitness",
    query: "Pull data from hevy and review my last workout",
    idealIntent: "HEALTH",
    idealCapability: "fitness",
    hints: { looks_like_health_fitness_read: true },
  },
  {
    category: "health_fitness",
    query: "recap my push workout from yesterday",
    idealIntent: "HEALTH",
    idealCapability: "fitness",
    hints: { looks_like_health_fitness_read: true },
  },
  {
    category: "health_fitness",
    query: "how was my gym session today?",
    idealIntent: "HEALTH",
    idealCapability: "fitness",
    hints: { looks_like_health_fitness_read: true },
  },
  {
    category: "health_hevy_write",
    query: "hevy routine: push day A",
    idealIntent: "HEALTH",
    idealCapability: "hevy_write",
    hints: {},
  },
  {
    category: "health_hevy_write",
    query: "hevy workout: legs and calves",
    idealIntent: "HEALTH",
    idealCapability: "hevy_write",
    hints: { looks_like_health_fitness_read: true },
  },
  {
    category: "health_nutrition",
    query: "how much protein should I aim for?",
    idealIntent: "HEALTH",
    idealCapability: "nutrition_advice",
    hints: {},
    magnusTools: false,
  },
  {
    category: "health_nutrition",
    query: "is intermittent fasting okay for me?",
    idealIntent: "HEALTH",
    idealCapability: "nutrition_advice",
    hints: {},
  },
  {
    category: "health_alternates",
    query: "vegan swap for paneer in this recipe",
    idealIntent: "HEALTH",
    idealCapability: "alternates",
    hints: {},
  },
  {
    category: "health_alternates",
    query: "instead of butter what can I use?",
    idealIntent: "HEALTH",
    idealCapability: "alternates",
    hints: {},
  },
  {
    category: "health_energy",
    query: "I'm exhausted and slept badly",
    idealIntent: "HEALTH",
    idealCapability: "energy",
    hints: {},
  },
  {
    category: "health_energy",
    query: "my HRV has been low all week",
    idealIntent: "HEALTH",
    idealCapability: "energy",
    hints: {},
  },
  {
    category: "health_journal",
    query: "wrap up my health day",
    idealIntent: "HEALTH",
    idealCapability: "journal",
    hints: {},
  },
  {
    category: "health_journal",
    query: "end of day health journal",
    idealIntent: "HEALTH",
    idealCapability: "journal",
    hints: {},
  },
  {
    category: "health_long_term",
    query: "16 week half marathon plan",
    idealIntent: "HEALTH",
    idealCapability: "long_term_planning",
    hints: {},
  },
  {
    category: "health_long_term",
    query: "build a season plan for strength",
    idealIntent: "HEALTH",
    idealCapability: "long_term_planning",
    hints: {},
  },

  // —— WEALTH ——
  {
    category: "wealth",
    query: "show my kite portfolio",
    idealIntent: "WEALTH",
    idealCapability: "coaching",
    hints: { looks_like_wealth_portfolio_read: true },
  },
  {
    category: "wealth",
    query: "show my net worth on kite",
    idealIntent: "WEALTH",
    idealCapability: "coaching",
    hints: { looks_like_wealth_portfolio_read: true },
  },
  {
    category: "wealth",
    query: "show my zerodha holdings",
    idealIntent: "WEALTH",
    idealCapability: "coaching",
    hints: { looks_like_wealth_portfolio_read: true },
  },
  {
    category: "wealth",
    query: "connect zerodha",
    idealIntent: "WEALTH",
    idealCapability: "kite_connect",
    hints: {},
  },
  {
    category: "wealth",
    query: "link kite account",
    idealIntent: "WEALTH",
    idealCapability: "kite_connect",
    hints: {},
  },
  {
    category: "wealth",
    query: "am I saving enough for retirement?",
    idealIntent: "WEALTH",
    idealCapability: "coaching",
    hints: {},
  },
  {
    category: "wealth",
    query: "how should I allocate my emergency fund?",
    idealIntent: "WEALTH",
    idealCapability: "coaching",
    hints: {},
  },
  {
    category: "wealth",
    query: "what is my cash flow this month?",
    idealIntent: "WEALTH",
    idealCapability: "coaching",
    hints: {},
  },
  {
    category: "wealth",
    query: "FIRE number for my lifestyle",
    idealIntent: "WEALTH",
    idealCapability: "coaching",
    hints: {},
  },
  {
    category: "wealth",
    query: "debt payoff vs investing tradeoff",
    idealIntent: "WEALTH",
    idealCapability: "coaching",
    hints: {},
  },

  // —— HAPPINESS ——
  {
    category: "happiness",
    query: "recommend a film like Arrival",
    idealIntent: "HAPPINESS",
    idealCapability: "recommendations",
    hints: {},
    magnusTools: false,
  },
  {
    category: "happiness",
    query: "books like Project Hail Mary",
    idealIntent: "HAPPINESS",
    idealCapability: "recommendations",
    hints: {},
    magnusTools: false,
  },
  {
    category: "happiness",
    query: "what game should I play this weekend?",
    idealIntent: "HAPPINESS",
    idealCapability: "recommendations",
    hints: {},
  },
  {
    category: "happiness",
    query: "music album for a rainy evening",
    idealIntent: "HAPPINESS",
    idealCapability: "recommendations",
    hints: {},
  },
  {
    category: "happiness",
    query: "poetry to read tonight",
    idealIntent: "HAPPINESS",
    idealCapability: "recommendations",
    hints: {},
  },
  {
    category: "happiness",
    query: "ideas for a restorative weekend",
    idealIntent: "HAPPINESS",
    idealCapability: "travel_rest",
    hints: {},
  },
  {
    category: "happiness",
    query: "weekend trip ideas near mountains",
    idealIntent: "HAPPINESS",
    idealCapability: "travel_rest",
    hints: {},
  },
  {
    category: "happiness",
    query: "how do I reconnect with an old friend?",
    idealIntent: "HAPPINESS",
    idealCapability: "relationships",
    hints: {},
  },
  {
    category: "happiness",
    query: "plan a low-stress vacation pace",
    idealIntent: "HAPPINESS",
    idealCapability: "travel_rest",
    hints: {},
  },
  {
    category: "happiness",
    query: "creative writing habit without burnout",
    idealIntent: "HAPPINESS",
    idealCapability: "creative_practice",
    hints: {},
  },
  {
    category: "happiness",
    query: "pick up guitar again for fun",
    idealIntent: "HAPPINESS",
    idealCapability: "creative_practice",
    hints: {},
  },
  {
    category: "happiness",
    query: "board game for 4 players",
    idealIntent: "HAPPINESS",
    idealCapability: "recommendations",
    hints: {},
  },
  {
    category: "happiness",
    query: "hobby ideas when I'm too tired to train",
    idealIntent: "HAPPINESS",
    idealCapability: "coaching",
    hints: {},
  },

  // —— WISDOM ——
  {
    category: "wisdom",
    query: "help me build a learning plan for Spanish",
    idealIntent: "WISDOM",
    idealCapability: "learning_plan",
    hints: {},
  },
  {
    category: "wisdom",
    query: "study plan for AWS cert",
    idealIntent: "WISDOM",
    idealCapability: "learning_plan",
    hints: {},
  },
  {
    category: "wisdom",
    query: "curriculum for learning Rust in 90 days",
    idealIntent: "WISDOM",
    idealCapability: "learning_plan",
    hints: {},
  },
  {
    category: "wisdom",
    query: "how do I ship my side project faster?",
    idealIntent: "WISDOM",
    idealCapability: "project_shipping",
    hints: {},
  },
  {
    category: "wisdom",
    query: "unblock my app launch",
    idealIntent: "WISDOM",
    idealCapability: "project_shipping",
    hints: {},
  },
  {
    category: "wisdom",
    query: "smallest next step on my portfolio site",
    idealIntent: "WISDOM",
    idealCapability: "project_shipping",
    hints: {},
  },
  {
    category: "wisdom",
    query: "prep for a promotion conversation",
    idealIntent: "WISDOM",
    idealCapability: "career_direction",
    hints: {},
  },
  {
    category: "wisdom",
    query: "how do I position for a senior role?",
    idealIntent: "WISDOM",
    idealCapability: "career_direction",
    hints: {},
  },
  {
    category: "wisdom",
    query: "deliberate practice routine for chess",
    idealIntent: "WISDOM",
    idealCapability: "skill_practice",
    hints: {},
  },
  {
    category: "wisdom",
    query: "daily practice drills for piano",
    idealIntent: "WISDOM",
    idealCapability: "skill_practice",
    hints: {},
  },
  {
    category: "wisdom",
    query: "career growth when feeling stuck",
    idealIntent: "WISDOM",
    idealCapability: "coaching",
    hints: {},
  },
  {
    category: "wisdom",
    query: "milestones for my open source project",
    idealIntent: "WISDOM",
    idealCapability: "project_shipping",
    hints: {},
  },

  // —— GENERAL: calendar & day ——
  {
    category: "general_calendar",
    query: "what's on my calendar tomorrow?",
    idealIntent: "GENERAL",
    idealCapability: "calendar",
    hints: {},
  },
  {
    category: "general_calendar",
    query: "what's on my calendar this week?",
    idealIntent: "GENERAL",
    idealCapability: "calendar",
    hints: {},
  },
  {
    category: "general_calendar",
    query: "schedule dentist Tuesday 3pm",
    idealIntent: "GENERAL",
    idealCapability: "calendar",
    hints: {},
  },
  {
    category: "general_calendar",
    query: "cancel my dentist appointment",
    idealIntent: "GENERAL",
    idealCapability: "calendar",
    hints: {},
  },
  {
    category: "general_calendar",
    query: "move team meeting to 4pm",
    idealIntent: "GENERAL",
    idealCapability: "calendar",
    hints: {},
  },
  {
    category: "general_calendar",
    query: "connect google",
    idealIntent: "GENERAL",
    idealCapability: "calendar",
    hints: {},
  },
  {
    category: "general_calendar",
    query: "connect calendar",
    idealIntent: "GENERAL",
    idealCapability: "calendar",
    hints: {},
  },
  {
    category: "general_day_overview",
    query: "what does my entire day look like tomorrow?",
    idealIntent: "GENERAL",
    idealCapability: "day_overview",
    hints: {},
    notes: "Holistic day — not HEALTH meal_plan_read",
  },
  {
    category: "general_day_overview",
    query: "what's on for the whole day Saturday?",
    idealIntent: "GENERAL",
    idealCapability: "day_overview",
    hints: {},
  },
  {
    category: "general_day_overview",
    query: "show me tomorrow: calendar, commitments, and meals",
    idealIntent: "GENERAL",
    idealCapability: "day_overview",
    hints: {},
  },
  {
    category: "general_day_overview",
    query: "what does my week look like?",
    idealIntent: "GENERAL",
    idealCapability: "day_overview",
    hints: {},
  },

  // —— GENERAL: YouTube ——
  {
    category: "general_youtube",
    query: "search YouTube for lo-fi study beats",
    idealIntent: "GENERAL",
    idealCapability: "youtube",
    hints: { looks_like_youtube_action: true },
    youtubeAction: true,
  },
  {
    category: "general_youtube",
    query: "search YouTube for jazz piano",
    idealIntent: "GENERAL",
    idealCapability: "youtube",
    hints: { looks_like_youtube_action: true },
    youtubeAction: true,
    magnusTools: false,
  },
  {
    category: "general_youtube",
    query: "add to wisdom playlist",
    idealIntent: "GENERAL",
    idealCapability: "youtube",
    hints: { looks_like_youtube_action: true },
    youtubeAction: true,
  },
  {
    category: "general_youtube",
    query: "bookmark this song on youtube",
    idealIntent: "GENERAL",
    idealCapability: "youtube",
    hints: { looks_like_youtube_action: true },
    youtubeAction: true,
  },
  {
    category: "general_youtube",
    query: "play next in cue queue",
    idealIntent: "GENERAL",
    idealCapability: "youtube",
    hints: { looks_like_youtube_action: true },
    youtubeAction: true,
  },
  {
    category: "general_youtube",
    query: "clear my magnus playlist",
    idealIntent: "GENERAL",
    idealCapability: "youtube",
    hints: { looks_like_youtube_action: true },
    youtubeAction: true,
  },
  {
    category: "general_youtube",
    query: "dedupe wisdom playlist",
    idealIntent: "GENERAL",
    idealCapability: "youtube",
    hints: { looks_like_youtube_action: true },
    youtubeAction: true,
  },
  {
    category: "general_youtube",
    query: "connect youtube",
    idealIntent: "GENERAL",
    idealCapability: "youtube",
    hints: { looks_like_youtube_action: true },
    youtubeAction: true,
  },
  {
    category: "general_youtube",
    query: "recommend songs on yt music for focus",
    idealIntent: "GENERAL",
    idealCapability: "youtube",
    hints: { looks_like_youtube_action: true },
    youtubeAction: true,
  },
  {
    category: "general_youtube",
    query: "https://youtube.com/watch?v=dQw4w9WgXcQ",
    idealIntent: "GENERAL",
    idealCapability: "youtube",
    hints: { looks_like_youtube_action: true },
    youtubeAction: true,
  },
  {
    category: "general_youtube",
    query: "show my happiness playlist",
    idealIntent: "GENERAL",
    idealCapability: "youtube",
    hints: { looks_like_youtube_action: true },
    youtubeAction: true,
  },

  // —— GENERAL: lists ——
  {
    category: "general_lists",
    query: "add Dune to my readlist",
    idealIntent: "GENERAL",
    idealCapability: "lists",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },
  {
    category: "general_lists",
    query: "what's on my watchlist?",
    idealIntent: "GENERAL",
    idealCapability: "lists",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },
  {
    category: "general_lists",
    query: "recommend a short thriller from my watchlist",
    idealIntent: "GENERAL",
    idealCapability: "lists",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },
  {
    category: "general_lists",
    query: "show my tasks list",
    idealIntent: "GENERAL",
    idealCapability: "lists",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },
  {
    category: "general_lists",
    query: "mark done on tasks list",
    idealIntent: "GENERAL",
    idealCapability: "lists",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },
  {
    category: "general_lists",
    query: "list_catalog",
    idealIntent: "GENERAL",
    idealCapability: "lists",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },
  {
    category: "general_lists",
    query: "what is on my food list",
    idealIntent: "GENERAL",
    idealCapability: "lists",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },
  {
    category: "general_lists",
    query: "recommend dinner from my food list",
    idealIntent: "GENERAL",
    idealCapability: "lists",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },
  {
    category: "general_lists",
    query: "add Inception to watchlist",
    idealIntent: "GENERAL",
    idealCapability: "lists",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },
  {
    category: "general_lists",
    query: "update readlist item Dune to done",
    idealIntent: "GENERAL",
    idealCapability: "lists",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },
  {
    category: "general_lists",
    query: "create_list weekend errands",
    idealIntent: "GENERAL",
    idealCapability: "lists",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },
  {
    category: "general_lists",
    query: "open my travel list",
    idealIntent: "GENERAL",
    idealCapability: "lists",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },
  {
    category: "general_lists",
    query: "show my music list",
    idealIntent: "GENERAL",
    idealCapability: "lists",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },

  // —— GENERAL: LifeOS ——
  {
    category: "general_lifeos",
    query: "log joy tank 72",
    idealIntent: "GENERAL",
    idealCapability: "lifeos",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },
  {
    category: "general_lifeos",
    query: "log joy tank",
    idealIntent: "GENERAL",
    idealCapability: "lifeos",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },
  {
    category: "general_lifeos",
    query: "health pillar is at_risk today",
    idealIntent: "GENERAL",
    idealCapability: "lifeos",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },
  {
    category: "general_lifeos",
    query: "wealth pillar deviating",
    idealIntent: "GENERAL",
    idealCapability: "lifeos",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },
  {
    category: "general_lifeos",
    query: "log this in my daily checkins",
    idealIntent: "GENERAL",
    idealCapability: "lifeos",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },
  {
    category: "general_lifeos",
    query: "save today's check-in",
    idealIntent: "GENERAL",
    idealCapability: "lifeos",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },
  {
    category: "general_lifeos",
    query: "add goal save for house",
    idealIntent: "GENERAL",
    idealCapability: "lifeos",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },
  {
    category: "general_lifeos",
    query: "list_lifeos_goals",
    idealIntent: "GENERAL",
    idealCapability: "lifeos",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },
  {
    category: "general_lifeos",
    query: "get_daily_checkin for today",
    idealIntent: "GENERAL",
    idealCapability: "lifeos",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },

  // —— GENERAL: Notion ——
  {
    category: "general_notion",
    query: "connect notion",
    idealIntent: "GENERAL",
    idealCapability: "notion",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },
  {
    category: "general_notion",
    query: "sync notion lists",
    idealIntent: "GENERAL",
    idealCapability: "notion",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },
  {
    category: "general_notion",
    query: "setup notion",
    idealIntent: "GENERAL",
    idealCapability: "notion",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },
  {
    category: "general_notion",
    query: "link notion for my lists",
    idealIntent: "GENERAL",
    idealCapability: "notion",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },

  // —— GENERAL: event log ——
  {
    category: "general_event_log",
    query: "reschedule my gym commitment to Friday",
    idealIntent: "GENERAL",
    idealCapability: "event_log",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },
  {
    category: "general_event_log",
    query: "log_event gym 7am tomorrow",
    idealIntent: "GENERAL",
    idealCapability: "event_log",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },
  {
    category: "general_event_log",
    query: "list_events this week",
    idealIntent: "GENERAL",
    idealCapability: "event_log",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },
  {
    category: "general_event_log",
    query: "update_event meditation done",
    idealIntent: "GENERAL",
    idealCapability: "event_log",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },
  {
    category: "general_event_log",
    query: "reschedule_event morning run to Sunday",
    idealIntent: "GENERAL",
    idealCapability: "event_log",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },
  {
    category: "general_event_log",
    query: "move my commitment to study to 8pm",
    idealIntent: "GENERAL",
    idealCapability: "event_log",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },

  // —— GENERAL: proactive ——
  {
    category: "general_proactive",
    query: "remind me tomorrow at 8pm to call mom",
    idealIntent: "GENERAL",
    idealCapability: "proactive",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },
  {
    category: "general_proactive",
    query: "remind me every day at 9am to stretch",
    idealIntent: "GENERAL",
    idealCapability: "proactive",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },
  {
    category: "general_proactive",
    query: "disable evening journal",
    idealIntent: "GENERAL",
    idealCapability: "proactive",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },
  {
    category: "general_proactive",
    query: "enable drift guard",
    idealIntent: "GENERAL",
    idealCapability: "proactive",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },
  {
    category: "general_proactive",
    query: "turn off stale list nudge",
    idealIntent: "GENERAL",
    idealCapability: "proactive",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },
  {
    category: "general_proactive",
    query: "remind me tonight at 9pm to journal",
    idealIntent: "GENERAL",
    idealCapability: "proactive",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
  },

  // —— GENERAL: journal & connect ——
  {
    category: "general_journal",
    query: "quick note: great meeting with design team",
    idealIntent: "GENERAL",
    idealCapability: "journal_note",
    hints: {},
  },
  {
    category: "general_journal",
    query: "log_note: idea for product roadmap",
    idealIntent: "GENERAL",
    idealCapability: "journal_note",
    hints: {},
  },
  {
    category: "general_zerodha",
    query: "connect zerodha from general",
    idealIntent: "GENERAL",
    idealCapability: "zerodha_connect",
    hints: {},
  },

  // —— GENERAL: pillar consultation ——
  {
    category: "general_pillar_consultation",
    query: "review my hevy workout and log this in my daily checkins",
    idealIntent: "GENERAL",
    idealCapability: "pillar_consultation",
    hints: { looks_like_magnus_tool_action: true, looks_like_health_fitness_read: true },
    magnusTools: true,
    consultPillars: ["HEALTH"],
  },
  {
    category: "general_pillar_consultation",
    query: "I am done with the workout. Read hevy, review, and log",
    idealIntent: "GENERAL",
    idealCapability: "pillar_consultation",
    hints: { looks_like_magnus_tool_action: true, looks_like_health_fitness_read: true },
    magnusTools: true,
    consultPillars: ["HEALTH"],
  },
  {
    category: "general_pillar_consultation",
    query: "add to watchlist and recommend a film like it",
    idealIntent: "GENERAL",
    idealCapability: "pillar_consultation",
    hints: { looks_like_magnus_tool_action: true },
    magnusTools: true,
    consultPillars: ["HAPPINESS"],
  },

  // —— GENERAL: conversation (no tools) ——
  {
    category: "general_conversation",
    query: "what's the capital of Portugal?",
    idealIntent: "GENERAL",
    idealCapability: "conversation",
    hints: {},
    magnusTools: false,
    youtubeAction: false,
  },
  {
    category: "general_conversation",
    query: "explain quantum entanglement simply",
    idealIntent: "GENERAL",
    idealCapability: "conversation",
    hints: {},
    magnusTools: false,
  },
  {
    category: "general_conversation",
    query: "thanks Magnus",
    idealIntent: "GENERAL",
    idealCapability: "conversation",
    hints: {},
    magnusTools: false,
  },
  {
    category: "general_conversation",
    query: "good morning",
    idealIntent: "GENERAL",
    idealCapability: "conversation",
    hints: {},
    magnusTools: false,
  },
  {
    category: "general_conversation",
    query: "what can you do?",
    idealIntent: "GENERAL",
    idealCapability: "conversation",
    hints: {},
    magnusTools: false,
  },
  {
    category: "general_conversation",
    query: "where should we eat on Saturday?",
    idealIntent: "HAPPINESS",
    idealCapability: "recommendations",
    hints: {},
    magnusTools: false,
    notes: "Classifier may choose HAPPINESS for social dining taste",
  },
  {
    category: "general_conversation",
    query: "tell me a joke",
    idealIntent: "GENERAL",
    idealCapability: "conversation",
    hints: {},
    magnusTools: false,
  },
  {
    category: "general_conversation",
    query: "summarize stoic philosophy",
    idealIntent: "GENERAL",
    idealCapability: "conversation",
    hints: {},
    magnusTools: false,
  },
];

/** Group catalog entries by category for reporting */
export function groupUserQueriesByCategory(): Record<string, UserQueryExpectation[]> {
  const out: Record<string, UserQueryExpectation[]> = {};
  for (const entry of USER_QUERY_CATALOG) {
    if (!out[entry.category]) {
      out[entry.category] = [];
    }
    out[entry.category].push(entry);
  }
  return out;
}
